// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhbFnzL-famLxFQPoTW8dA78z_-9QFjE',
    appId: '1:138804168879:web:00a64bc77a506fabc4ec5a',
    messagingSenderId: '138804168879',
    projectId: 'face-recognition-cdb26',
    authDomain: 'face-recognition-cdb26.firebaseapp.com',
    storageBucket: 'face-recognition-cdb26.appspot.com',
    measurementId: 'G-8NDZKCPX7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NqV8HsMOEOQ4j0iqfa8mbhXA7kcR6jQ',
    appId: '1:138804168879:android:c760da13434183cfc4ec5a',
    messagingSenderId: '138804168879',
    projectId: 'face-recognition-cdb26',
    storageBucket: 'face-recognition-cdb26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUhoYSKNGttitIsCday1Sc5-wkCi1Shkg',
    appId: '1:138804168879:ios:c52902bcda316b2cc4ec5a',
    messagingSenderId: '138804168879',
    projectId: 'face-recognition-cdb26',
    storageBucket: 'face-recognition-cdb26.appspot.com',
    iosClientId: '138804168879-od712p4fau8a3oucuj1q9l5rkriv6i0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.deetct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUhoYSKNGttitIsCday1Sc5-wkCi1Shkg',
    appId: '1:138804168879:ios:c52902bcda316b2cc4ec5a',
    messagingSenderId: '138804168879',
    projectId: 'face-recognition-cdb26',
    storageBucket: 'face-recognition-cdb26.appspot.com',
    iosClientId: '138804168879-od712p4fau8a3oucuj1q9l5rkriv6i0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.deetct',
  );
}
